### ISSUE TITLE
为什么在 localhost 也会注入插件

### ISSUE THREAD

**Issue by shoyuf** [EVINK/Dingtalk-Assistant#3]
最近有什么更新内容了吗？

localhost 开发页面也报错了

Uncaught (in promise) TypeError: Cannot read property 'banGlobalStyle' of undefined
    at s.<anonymous> (generalPageContent.js:1)

**Comment by EVINK** [comment]
抱歉，这是一个bug，我已经发布新版本解决它了。你可以到设置页面点一下保存按钮来解决它
