### ISSUE TITLE
消息提示会挂掉

### ISSUE THREAD

**Issue by EVINK** [EVINK/Dingtalk-Assistant#5]
用了一段时间后，新消息提示会挂掉

**Comment by wyy0117** [comment]
现在是没有消息提示功能了吗？

**Comment by EVINK** [comment]
已经尝试修复了，目前还在测试中，估计一周左右会在商店更新。也可以直接在 扩展程序 -> 加载已解压的扩展程序，选择 app/ 来使用修复的版本 （正好帮我测试一下😂）

谢谢你对这个项目的关注，爱你哟❤️

**Comment by EVINK** [comment]
> 现在是没有消息提示功能了吗？

已经尝试修复了，目前还在测试中，估计一周左右会在商店更新。也可以直接在 扩展程序 -> 加载已解压的扩展程序，选择 app/ 来使用修复的版本 （正好帮我测试一下😂）

谢谢你对这个项目的关注，爱你哟❤️

**Comment by wyy0117** [comment]
> > 现在是没有消息提示功能了吗？
> 
> 已经尝试修复了，目前还在测试中，估计一周左右会在商店更新。也可以直接在 扩展程序 -> 加载已解压的扩展程序，选择 app/ 来使用修复的版本 （正好帮我测试一下）
> 
> 谢谢你对这个项目的关注，爱你哟

好的，辛苦了，测试结果我会及时反馈。

**Comment by wyy0117** [comment]
经测试，我这边无消息提示，系统是linux，版本：deepin15.11,chrome版本：78
另外换背景色，全屏都是无效的。
我钉钉号：wyy349093330

**Comment by EVINK** [comment]
> 经测试，我这边无消息提示，系统是linux，版本：deepin15.11,chrome版本：78
> 另外换背景色，全屏都是无效的。
> 我钉钉号：wyy349093330

看起来插件没有被启用，你的网页版钉钉的地址栏带了参数吗？如果带了参数去掉参数后刷新网页再试一下

**Comment by wyy0117** [comment]
去掉参数，确实可以改背景，可以全屏了，但是仍然无消息提示

**Comment by EVINK** [comment]
> 去掉参数，确实可以改背景，可以全屏了，但是仍然无消息提示

控制台或者是插件的背景页面有来自 dingTalkContent.js: 的报错信息吗？

**Comment by wyy0117** [comment]
没有报错，console下一直在打印日志:0  ，好几千条了，一直在增加

**Comment by EVINK** [comment]
> 没有报错，console下一直在打印日志:0 ，好几千条了，一直在增加

能截个图到这里看一下吗？

**Comment by wyy0117** [comment]
![image](https://user-images.githubusercontent.com/19330823/75305376-dde43480-5880-11ea-960b-ed55df3a4718.png)

**Comment by EVINK** [comment]
这个不是我打印的日志，可能是别的插件打的。

之前遇到过的都是丢通知的问题，但完全没有通知的这个还是第一次遇见，所以目前我也没有太好的解决思路，我只能建议：
1.  完全移除钉钉助手（开发版1.2.2和正式版1.2.1）
2. 完全退出Chrome浏览器
3. 重新加载钉钉助手开发版
4. 使用钉钉助手的“去网页版”打开钉钉，并扫描登陆
5. 登陆过后暂时不要进行操作，使用另一个账号发送消息，以测试通知是否正常运作

最后如果还是不能正常接受通知，我推荐你使用更为成熟的 [钉钉Electron应用](https://github.com/nashaofu/dingtalk) 相信一定能解决你的需求

thanks for your time ~

**Comment by wyy0117** [comment]
好的，谢谢作者大大。

其实我最想要的就是钉钉的通知提醒功能，最好是托盘能有消息闪烁的那种通知，electro的钉钉现在因为消息闪烁会卡死自动退出 ，暂未解决，所以只能使用浏览器的网页版。

 其实网页版钉钉的痛点很大一部分就是来消息无法及时得到通知，像微信qq这种都有托盘图标，来消息会闪烁，基本不会错过什么消息。所以作者可以考虑插件可以显示托盘图标（我不知道能不能实现，我瞎YY的）
